formatter: markdown table

output:
  file: README.md
  mode: inject

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  required: true
  sensitive: true
  type: true
